### ISSUE TITLE
How to get Docker container working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [russelljjarvis/ScienceAccess#1]
Hi @russelljjarvis 

Based on your mail I tried to follow the instructions on the github front page. So I git cloned, docker build and docker run the application. I could see I could not access the application at localhost:8080.

In order to get that working I needed to change a few things

#### Dockerfile

```bash
RUN bash -c 'echo -e "\
	[server]\n\
	enableCORS = false\n\
	enableXsrfProtection = false\n\
	\n\
	[browser]\n\
	serverAddress = \"0.0.0.0\"\
	" > /root/.streamlit/config.toml'
```

#### Command line

```bash
docker run -p 8080:8080 --shm-size=3gb --cpus=2.0 --memory=1g --memory-swa
p=1g --rm wcomplexity
```

You can see the changes below including the app running on localhost:8080

![image](https://user-images.githubusercontent.com/42288570/90371513-5fb65d00-e06f-11ea-9f29-3107e44ec4f8.png)

**Comment by russelljjarvis** [comment]
Wow! thanks so much for looking into this Marc! I also prefer GH issues as a place to resolve code issues

**Comment by russelljjarvis** [comment]
I have merged this change into the repository. I wonder if you are using Docker on OSX or Linux? I have found docker on OSX to be more complicated with regards to localhost forwarding and networking.

**Comment by MarcSkovMadsen** [comment]
I’m on windows
