### ISSUE TITLE
Some ideas for improvements

### ISSUE THREAD

**Issue by MarcSkovMadsen** [russelljjarvis/ScienceAccess#2]
I like your README. It is very useable. A few things could improve it.

- Please state the license and add a LICENSE file.
    - I might develop a similar version in Panel one day because I like you app and I like Panel :-) But I don't know if you want or like that without a license specification.
- Please comment on `docker run` that the user should not set cpus to something higher than what is available on his/ hers machine. I only have 2 cpus so I got error message using the specified 4 cpus.
- Consider moving the .gif video a little bit higher and maybe even changing it to an embedded .mp4 video where you share you vision and the resulting app. A picture says more than a thousand words. And a video might say even more :-)

**Comment by russelljjarvis** [comment]
That would be awesome if you want to develop a similar app and derive from this code in any way.

This tool is heavily dependent on Free and Open Source code so I thought our licence should be similar to the tools  we have built on top of. I don't think anyone intends to use this code/tool for profit. I think its more like for academic use/research/intellectual curiosity.

I believe I previously wrote that the [licence was MIT](https://github.com/russelljjarvis/ScienceAccess/blob/master/license.md), but actually maybe we need advice about that. I don't really know what a good licence is. What would you use? Is MIT any good in your experience?

Also please note if you are playing around with it I think I have introduced a transient bug in the readability metrics, so scraped results may not look right as of today, but the scraped results usually look sensible relative to the ARTCORPUS, and the benchmarks. We are really into feedback and ideas for improvements, especially from developers.

**Comment by russelljjarvis** [comment]
We could use the Attribution-ShareAlike 4.0 International licence too. What do you think @mcgurrgurr?
We are working on improving the resolution of the git too.

**Comment by russelljjarvis** [comment]
@all-contributors please add @MarcSkovMadsen for design, ideas and infra

**Comment by russelljjarvis** [comment]
@all-contributors please add @mcgurrgurr for code, doc, ideas, design and infra

**Comment by russelljjarvis** [comment]
@all-contributors please add @russelljjarvis for code, doc, ideas, design and infra

**Comment by russelljjarvis** [comment]
@all-contributors please add @mcgurrgurr for code, doc, ideas, design and infra
