### ISSUE TITLE
readability of README issues.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/ScienceAccess#4]
https://github.com/russelljjarvis/ScienceAccess/commit/6d3b478ffd4602d04514f0e64c1993a9b58ddd49

> Understanding a big word is hard, so when big ideas are written down with lots of big words, the large pile of big words is also hard to understand. We used a computer to quickly visit and read many different websites to see how hard each piece of writing was to understand. People may avoid learning hard ideas, only because there are too many hard words. We think we can help by explaining the problem with smaller words, and by creating tools to address the problem.

--the original version of that paragraph was made with the upgoer 5 editor using only 10,000 of the most common English words. It might have sounded a bit condescending but we have to write something this basic for internal consistency.

"Data-driven" is an important term for a manuscript but its very scientific and big word.

Also, I believe we need to change "[constraints on conceptual references](https://github.com/russelljjarvis/ScienceAccess/blob/master/main.py#L146
)" to just grammatically correct Nonesense.

@mcgurrgurr

**Comment by mcgurrgurr** [comment]
Yes I agree that it should be in plain language. I did cater the edits to fit the grade level to be grade 8. So this should be accomplished.
